### ISSUE TITLE
wiki

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [redeyeteam/bentoo#3]
Can't access https://bitbucket.org/redeyeteam/bentoo/wiki

**Comment by init6** [comment]
@Alessandro-Barbieri there is no any wiki

**Comment by Alessandro-Barbieri** [comment]
Why it's referenced in bentoo-sources.eclass line 20?

**Comment by init6** [comment]
bentoo-sources.eclass based on geek-sources.eclass. And sed make nice replace to me.

**Comment by init6** [comment]
@Alessandro-Barbieri bentoo-sources almost the same as vanilla except USE="brand" install [icons](https://init-6.bitbucket.io/content/2017/01/%D0%9E%D1%87%D0%B5%D1%80%D0%B5%D0%B4%D0%BD%D0%BE%D0%B5-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-bentoo-sources/) (from zen-kernel, old kernel sources + Larry the cow) [Ka-Ping Yee ISO Latin-1 Font](https://init-6.bitbucket.io/content/2010/10/ka-ping-yee-iso-latin-1-font-in-linux-kernel/) + colored-printk (from zen-kernel)
