### ISSUE TITLE
add overlay to layman list

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [redeyeteam/bentoo#4]
Never thought to add the overlay to tha layman list?

**Comment by init6** [comment]
@Alessandro-Barbieri 

0) layman is  obsolete and not needed with `/etc/portage/repos.conf/* `

1) overlay is unstable and can brake everything

2) bentoo and gentoo have absolutely different goals, solutions and approaches

And most importantly, We do not want to involved in the bureaucracy gentoo.
